spring.application.name=JSystems-SilkyCodders-1

# Local Postgres from ../compose.yaml
spring.datasource.url=jdbc:postgresql://localhost:5433/sample_app
spring.datasource.username=app_user
spring.datasource.password=app_password_123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
